version: '2'

services:

    todo_web:
        build: ./source/
        container_name: todo_web 
        restart: always
        depends_on:
            - todo_mysql
            - todo_mysql_data
        links:
            - todo_mysql:mysql
        volumes:
            - ./source/:/usr/src/app
        env_file: .env
        environment:
            DEBUG: 'true'
        command: /usr/local/bin/gunicorn todolist.wsgi:application -w 2 -b :8000 --reload


    todo_nginx:
        build: ./nginx/
        container_name: todo_nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - ./source/staticfiles/:/www/static
            - ./nginx/sites-enabled/:/etc/nginx/sites-enabled
        depends_on:
            - todo_web
        links:
        - todo_web:web


    todo_mysql_data:
        image: mysql:5.7
        container_name: todo_mysql_data
        entrypoint: /bin/bash


    todo_mysql:
        image: mysql:5.7
        container_name: todo_mysql
        restart: always
        depends_on:
            - todo_mysql_data
        volumes_from:
            - todo_mysql_data
        environment:
            MYSQL_DATABASE: todo_app
            MYSQL_USER: todo_user
            MYSQL_PASSWORD: todo@2016!
            MYSQL_ROOT_PASSWORD: Selenite#1