# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Pending Info', 'Pending Info'), ('Inactive', 'Inactive'), ('Active', 'Active')], default='Pending Info', max_length=25),
        ),
    ]
