# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_insurance_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='upload',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
    ]
