# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='upload',
        ),
        migrations.AlterField(
            model_name='company',
            name='insurance_file',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
    ]
